///
/// A label is a storage location used to keep the value of a value that's generated by
///
#[derive(Copy, Clone, PartialEq, Eq, Hash)]
pub struct Label {
    id: u64
}

impl Label {
    ///
    /// Creates a new label
    ///
    pub fn with_id(id: u64) -> Label { Label { id } }
}
