use super::action::*;

use smallvec::*;

///
/// Represents the actions generated by a compilation stage
///
#[derive(Clone)]
pub struct CompiledActions {
    /// The actions to perform when setting up a new frame
    pub frame_setup: SmallVec<[Action; 8]>,

    /// The actions to perform for this step (setting the result)
    pub actions: SmallVec<[Action; 8]>,
}
