[package]
name        = "safas"
version     = "0.1.0"
authors     = ["Andrew Hunter <andrew@logicalshift.io>"]
edition     = "2018"
license     = "Apache-2.0"

[dependencies]
lazy_static = "1.4"
smallvec    = "0.6"
